# Creating multi diemensional array

In [1]:
import numpy as np

x = np.arange(0,3)
y = np.arange(3,6)
z = np.arange(6,9)

In [2]:
array_multi = np.array([x,y,z])
print(array_multi)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
print(array_multi.dtype)

int32
