# Numpy Multidimensional slicing

In [1]:
import numpy as np

x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
# accessing an elemnt
x[1,2]

5

In [3]:
y = np.arange(18).reshape(3,2,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [4]:
y[2,1,1]

16

In [5]:
y[1,0:,]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
y[1,0:2,0:3]  # another way

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
y[1,0:,0:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
y[1,:,:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
y[1,...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
y[:,0,0]

array([ 0,  6, 12])

## Step

In [11]:
y[1,:,:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
y[1,:,:3:2]

array([[ 6,  8],
       [ 9, 11]])

## Comparision operation

In [13]:
comparision = y>6
print(comparision)

[[[False False False]
  [False False False]]

 [[False  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [14]:
y[comparision]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [15]:
y[y>6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

## other functions

In [16]:
y.max()

17

In [17]:
y.min()

0