# Matrix Multiplication

In [1]:
import numpy as np

In [2]:
mat_x = np.matrix([2,2,4,5,1,0]).reshape(2,3)
mat_x

matrix([[2, 2, 4],
        [5, 1, 0]])

In [3]:
mat_y = np.matrix([0,2,4,6,1,4]).reshape(3,2)
mat_y

matrix([[0, 2],
        [4, 6],
        [1, 4]])

In [4]:
mat_x * mat_y

matrix([[12, 32],
        [ 4, 16]])

In [5]:
mat_product = np.matmul(mat_x,mat_y)
mat_product

matrix([[12, 32],
        [ 4, 16]])

## We can run same using the numpy arrays also

In [6]:
x = np.array([2,2,4,5,1,0]).reshape(2,3)
x

array([[2, 2, 4],
       [5, 1, 0]])

In [7]:
y = np.matrix([0,2,4,6,1,4]).reshape(3,2)
y

matrix([[0, 2],
        [4, 6],
        [1, 4]])

In [8]:
x*y

matrix([[12, 32],
        [ 4, 16]])

In [9]:
product = np.matmul(x,y)
product

matrix([[12, 32],
        [ 4, 16]])

In [10]:
x@y

matrix([[12, 32],
        [ 4, 16]])