# Numpy reshape

In [1]:
import numpy as np

x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [2]:
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
print(x.reshape(3,-1))  # when we don't know number of elements ( coloumns)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
y = np.arange(18)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [5]:
print(y.reshape(2,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [6]:
print(y.reshape(3,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [7]:
print(y.reshape(3,2,3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
