# Numpy - Stacking

In [1]:
import numpy as np

## horizontal stack

In [2]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [4]:
c = np.hstack((a,b))
c

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3]])

### using contatenate

In [5]:
d = np.concatenate((a,b), axis = 1)
d

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3]])

### using the column stack

In [6]:
e = np.column_stack((a,b))
e

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3]])

## Vertical stack

In [7]:
x = np.arange(6).reshape(3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
y = np.arange(4).reshape(2,2)
y

array([[0, 1],
       [2, 3]])

In [9]:
z = np.vstack((x,y))
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3]])

In [10]:
z.shape

(5, 2)

### using concatenate

In [11]:
p = np.concatenate((x,y), axis = 0)
p

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3]])

In [12]:
q = np.row_stack((x,y))
q

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3]])

## comparing the two

In [13]:
print(z==p)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


## Depth stack ( adds additional dimension)

In [14]:
m = np.arange(4).reshape(2,2)
m

array([[0, 1],
       [2, 3]])

In [15]:
n = np.arange(4).reshape(2,2)*2
#n = n*2
n

array([[0, 2],
       [4, 6]])

In [16]:
o = np.dstack((m,n))
o

array([[[0, 0],
        [1, 2]],

       [[2, 4],
        [3, 6]]])

In [17]:
o.shape

(2, 2, 2)