# Manipulating the array shapes

## ravel

In [1]:
import numpy as np

x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
revelled_x = x.ravel()
print(revelled_x)

[0 1 2 3 4 5 6 7 8]


## flatten

In [3]:
flattend_x = x.flatten()
print(flattend_x)

[0 1 2 3 4 5 6 7 8]


## difference

### ravel won't allocate new memory and changes will change the x it self

In [4]:
revelled_x[2]=999
print(revelled_x)

[  0   1 999   3   4   5   6   7   8]


In [5]:
print(x)

[[  0   1 999]
 [  3   4   5]
 [  6   7   8]]


### flatten creates a copy of it

In [6]:
z = np.arange(9).reshape(3,3)

In [7]:
flattend_z = z.flatten()
print(flattend_z)

[0 1 2 3 4 5 6 7 8]


In [8]:
flattend_z[2]=999
print(flattend_z)

[  0   1 999   3   4   5   6   7   8]


In [9]:
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## reshape

In [10]:
y = np.arange(9)
y.shape = [3,3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## transpose

In [11]:
print(y.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [12]:
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


## re-size

In [13]:
print(np.resize(y,(6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [14]:
print(np.resize(y,(2,3)))

[[0 1 2]
 [3 4 5]]


In [15]:
np.zeros((6,))

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((6,), dtype = int)

array([0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones((2,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3,4)  # between the 0 & 1 

array([[0.31675005, 0.2332879 , 0.943093  , 0.07233804],
       [0.86091464, 0.06800934, 0.4603589 , 0.54771012],
       [0.28031208, 0.08592838, 0.01997412, 0.47932995]])