# Why Numpy arrays ? ( as compared to the python list )

## list operations without numpy

In [1]:
list_for_square = list(range(1,4))
list_for_square

[1, 2, 3]

In [2]:
list_for_cubes = list(range(1,4))
list_for_cubes

[1, 2, 3]

In [3]:
list_for_sums = []

In [4]:
for i in range(3):
    list_for_square[i] = list_for_square[i] **2
    list_for_cubes[i] = list_for_cubes[i] **3
    list_for_sums.append(list_for_square[i]+list_for_cubes[i])

In [5]:
list_for_square

[1, 4, 9]

In [6]:
list_for_cubes

[1, 8, 27]

In [7]:
list_for_sums

[2, 12, 36]

## Let us do the same thing using Numpy

In [8]:
import numpy as np

In [9]:
array_for_square = np.arange(1,4)**2
print(array_for_square)

[1 4 9]


In [10]:
array_for_cube = np.arange(1,4)**3
print(array_for_cube)

[ 1  8 27]


In [11]:
array_for_sums = array_for_square + array_for_cube
print(array_for_sums)

[ 2 12 36]


## Let us explore few more Numpy things

In [12]:
array_sample = np.arange(1,4)
print(array_sample)

[1 2 3]


In [13]:
print(np.power(array_sample,2))

[1 4 9]


In [14]:
print(np.power(array_sample,3))

[ 1  8 27]


In [15]:
print(np.exp(array_sample))

[ 2.71828183  7.3890561  20.08553692]


In [16]:
print(np.negative(array_sample))

[-1 -2 -3]


In [17]:
print(np.tan(array_sample))

[ 1.55740772 -2.18503986 -0.14254654]


In [18]:
print(np.log(array_sample))

[0.         0.69314718 1.09861229]
