# Numpy - Slicing

In [1]:
import numpy as np

x = np.arange(11,20)
print(x)

[11 12 13 14 15 16 17 18 19]


In [2]:
print(x[:5])

[11 12 13 14 15]


In [3]:
print(x[2:5])

[13 14 15]


In [4]:
print(x[1:9:2])

[12 14 16 18]


In [5]:
print(x[6:])

[17 18 19]
